name: Integration Tests

on: pull_request

jobs:
  integration_tests:
    name: Integration tests
    # uses: uc-cdis/.github/.github/workflows/integration_tests.yaml@master
    uses: uc-cdis/gen3-code-vigil/.github/workflows/shared_integration_tests.yaml@chore/custom_cloud_auto_branch
    with:
      SERVICE_TO_TEST: graph_submission
      CLOUD_AUTO_BRANCH: chore/fence_create_add_poetry_run
      TEST_REPO_BRANCH: chore/custom_cloud_auto_branch
    secrets:
      CI_TEST_ORCID_USERID: ${{ secrets.CI_TEST_ORCID_USERID }}
      CI_TEST_ORCID_PASSWORD: ${{ secrets.CI_TEST_ORCID_PASSWORD }}
      CI_TEST_RAS_EMAIL: ${{ secrets.CI_TEST_RAS_EMAIL }}
      CI_TEST_RAS_PASSWORD: ${{ secrets.CI_TEST_RAS_PASSWORD }}
      CI_TEST_RAS_2_EMAIL: ${{ secrets.CI_TEST_RAS_2_EMAIL }}
      CI_TEST_RAS_2_PASSWORD: ${{ secrets.CI_TEST_RAS_2_PASSWORD }}
      CI_SLACK_BOT_TOKEN: ${{ secrets.CI_SLACK_BOT_TOKEN }}
      CI_SLACK_CHANNEL_ID: ${{ secrets.CI_SLACK_CHANNEL_ID }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
